const colors = {
  radius: 0,
  light: {
    text: "#0f172a",
    tint: "#0f172a",
    background: "#ffffff",
    foreground: "#0f172a",
    card: "#f8fafc",
    cardForeground: "#0f172a",
    primary: "#0f172a",
    primaryForeground: "#ffffff",
    secondary: "#f1f5f9",
    secondaryForeground: "#0f172a",
    muted: "#f8fafc",
    mutedForeground: "#64748b",
    accent: "#f1f5f9",
    accentForeground: "#0f172a",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e2e8f0",
    input: "#e2e8f0",
    ring: "#0f172a",
    radius: 0,
    tabIconDefault: "#94a3b8",
    tabIconSelected: "#0f172a",
  },
  dark: {
    text: "#f8fafc",
    tint: "#ffffff",
    background: "#0a0a0a",
    foreground: "#f8fafc",
    card: "#161616",
    cardForeground: "#f8fafc",
    primary: "#f8fafc",
    primaryForeground: "#0f172a",
    secondary: "#1e293b",
    secondaryForeground: "#f8fafc",
    muted: "#1a1a1a",
    mutedForeground: "#94a3b8",
    accent: "#1e293b",
    accentForeground: "#f8fafc",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#1e293b",
    input: "#1e293b",
    ring: "#f8fafc",
    radius: 0,
    tabIconDefault: "#64748b",
    tabIconSelected: "#f8fafc",
  },
};

export default colors;
